### ISSUE TITLE
simple_response fulfillment message type unsupported in API

### ISSUE THREAD

**Issue by pmioulet** [api-ai/apiai-java-client#24]
Sometimes(I'm not sure when and why) on a query request, the api.ai replies with the following content in the fulfillment bloc. Notice that the type tag is simple_response for the first response and a number for the other ones.

`
...
    "fulfillment": {
      "speech": "resize my aws server i-XXXXX to m4.xlarge",
      "messages": [
        {
          "type": "simple_response",
          "platform": "google",
          "textToSpeech": "resize my aws server i-XXXXX to m4.xlarge"
        },
        {
          "type": 0,
          "platform": "facebook",
          "speech": "resize my aws server i-XXXXX to m4.xlarge"
        },
...
`

The problem is that the java client does not seem to support this and fails with a NumberFormatException:

`
java.lang.NumberFormatException: For input string: "simple_response"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0_111]
  at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0_111]
  at java.lang.Integer.parseInt(Integer.java:615) ~[na:1.8.0_111]
  at com.google.gson.JsonPrimitive.getAsInt(JsonPrimitive.java:260) ~[gson-2.8.0.jar!/:na]
  at ai.api.GsonFactory$ResponseItemAdapter.deserialize(GsonFactory.java:78) ~[libai-1.4.8.jar!/:na]
  at ai.api.GsonFactory$ResponseItemAdapter.deserialize(GsonFactory.java:71) ~[libai-1.4.8.jar!/:na]
  at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.Gson.fromJson(Gson.java:887) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.Gson.fromJson(Gson.java:852) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.Gson.fromJson(Gson.java:801) ~[gson-2.8.0.jar!/:na]
  at com.google.gson.Gson.fromJson(Gson.java:773) ~[gson-2.8.0.jar!/:na]
`

**Comment by folomeev** [comment]
Committed initial support into `master` branch. You may try to assembly the latest version of the library and check again.

**Comment by pmioulet** [comment]
Thanks, it looks like this fixed the issue

**Comment by folomeev** [comment]
Fix published on Maven repository
