### ISSUE TITLE
Gson deserialization issue

### ISSUE THREAD

**Issue by Premier** [api-ai/apiai-java-client#27]
Hi,
i'm unable to deserialize AIResponse from String.
I'm using SDK 1.4.9 with Gson version 2.8.1

My code is
```
Gson jsoner = new Gson();
AIResponse aiResponse = jsoner.fromJson(requestData, AIResponse.class);
```

requestData is the json received in webhook method.

The exception is
```
RuntimeException: Unable to invoke no-args constructor for class ai.api.model.ResponseMessage. Register an InstanceCreator with Gson for this type may fix this problem.] with root cause
java.lang.UnsupportedOperationException: Abstract class can't be instantiated! Class name: ai.api.model.ResponseMessage
        at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:120)
        at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
        at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
```

**Comment by folomeev** [comment]
Try to use `ai.api.GsonFactory`:

```java
Gson jsoner = GsonFactory.getDefaultFactory().getGson();
AIResponse aiResponse = jsoner.fromJson(requestData, AIResponse.class);
```

**Comment by devmichaelgirgis** [comment]
any help?
I have the same issue with android with retrofit lib!
